export enum TipoVinculo {
  'GRADUACAO' = 'GRADUACAO',
  'POS_GRADUACAO' = 'POS_GRADUACAO',
  'POS_DOUTORADO' = 'POS_DOUTORADO',
  'DOCENTE' = 'DOCENTE',
  'PESQUISADOR' = 'PESQUISADOR',
  'INCUBACAO' = 'INCUBACAO',
}
